export const EXAMPLES_TO_TEST = [
  'HelloTriangle',
  'HelloTriangleMSAA',
  'RotatingCube',
  'TwoCubes',
  'TexturedCube',
  'InstancedCube',
  'FractalCube',
  'CubeMap',
  // GPGPU
  'ComputeBoids',
  'GameOfLife',
  'BitonicSort',
  // WebGPUFeatures
  'SamplerParameters',
  'ReversedZ',
  'RenderBundles',
  'OcclusionQueries',
  // GraphicsTechniques
  'Cameras',
  'NormalMap',
  'ShadowMapping',
  'DeferredRendering',
  'ParticlesHDR',
  'ImageBlur',
  'Cornell',
  'ABuffer',
  'SkinnedMesh',
  'VolumeRendering',
  'Wireframe',
  // InHouse
  'FlakesTexture',
  'Crop',
  'Video',
  'Outlines',
  'Portal',
  'CWTriangle',
  'ClearBuffer',
  'ResizeCanvas',
  'AnimateCanvas',
];
